const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const BASE='http://127.0.0.1:8790/';
const results=[];
async function run(browser,name,viewport,mobile=false) {
 const context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,locale:'en-US',reducedMotion:'reduce'});
 const page=await context.newPage();const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('response',r=>{if(r.status()>=400&&!/\/favicon\.ico(?:\?|$)/.test(r.url()))errors.push(`${r.status()} ${r.url()}`)});
 await page.goto(BASE,{waitUntil:'networkidle'});
 await page.locator('#btn-task-freeplay').click();
 await page.locator('#input-nickname').fill(name);
 await page.locator('#btn-start-task').click();
 await page.locator('body.in-room').waitFor();
 const save=new URL(page.url()).searchParams.get('solo');assert.ok(save);
 if(mobile) await page.locator('#btn-mobile-controls').click();
 await page.locator('#btn-control-settings').click();
 await page.locator('#control-settings-overlay:not(.hidden)').waitFor();
 for(let i=0;i<18;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('#control-settings-overlay').contains(document.activeElement)),true,`settings focus escaped at ${i}`)}
 await page.screenshot({path:path.join(__dirname,`${name}-settings.jpg`),type:'jpeg',quality:72,fullPage:true});
 await page.locator('#control-center-mode-toggle').click();
 assert.equal(await page.locator('#control-center-mode-toggle').getAttribute('aria-checked'),'false');
 await page.locator('#btn-control-settings-save').click();
 await page.locator('#control-settings-overlay').waitFor({state:'hidden'});
 assert.equal(await page.locator('#btn-control-settings').evaluate(x=>x===document.activeElement),true,'focus did not return to settings opener');
 if(mobile){
   await page.locator('#btn-mobile-flag').click();
   const before=await page.locator('#mobile-stat-mines').innerText();
   const box=await page.locator('#canvas-container canvas').boundingBox();
   await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);
   await page.waitForFunction(prev=>document.querySelector('#mobile-stat-mines').textContent.trim()!==prev,before);
   const flagged=await page.locator('#mobile-stat-mines').innerText();
   await page.screenshot({path:path.join(__dirname,`${name}-flag.jpg`),type:'jpeg',quality:72,fullPage:true});
   await page.locator('#btn-mobile-dig').click();
   await page.locator('#btn-mobile-slices').click();assert.equal(await page.locator('#slicing-panel').evaluate(x=>x.classList.contains('mobile-open')),true);
   await page.locator('#btn-close-slices').click();
   await page.locator('#btn-mobile-mission').click();assert.equal(await page.locator('#social-panel').evaluate(x=>x.classList.contains('mobile-open')),true);
   await page.locator('#btn-mobile-mission').click();
   const beforeGestureMines=await page.locator('#mobile-stat-mines').innerText();
   const beforeGestureProgress=await page.locator('#mobile-stat-progress').innerText();
   const cdp=await context.newCDPSession(page);
   const x=Math.round(box.x+box.width/2),y=Math.round(box.y+box.height/2);
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});
   await page.waitForTimeout(520);
   await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+14,y:y+10,id:1}]});
   await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
   await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-35,y,id:1},{x:x+35,y,id:2}]});
   await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-50,y:y+9,id:1},{x:x+50,y:y+9,id:2}]});
   await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
   assert.equal(await page.locator('#mobile-stat-mines').innerText(),beforeGestureMines);
   assert.equal(await page.locator('#mobile-stat-progress').innerText(),beforeGestureProgress);
   await page.setViewportSize({width:844,height:390});
   assert.equal(await page.locator('body.in-room').count(),1);
   await page.setViewportSize(viewport);
   assert.equal(new URL(page.url()).searchParams.get('solo'),save);
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth<=1),true);
   await page.screenshot({path:path.join(__dirname,`${name}-board.jpg`),type:'jpeg',quality:72,fullPage:true});
   results.push({name,viewport,flagBefore:before,flagAfter:flagged,mobilePanels:true,touchHoldAndPan:true,twoFingerGesture:true,boardStateUnchangedAfterGestures:true,orientationPreserved:true,focusTrap:true,errors,passed:true});
 } else {
   await page.locator('#btn-mode-flag').click();
   const before=await page.locator('#stat-mines').innerText();
   const canvas=page.locator('#canvas-container canvas');const box=await canvas.boundingBox();
   await canvas.click({position:{x:box.width/2,y:box.height/2}});
   await page.waitForFunction(prev=>document.querySelector('#stat-mines').textContent.trim()!==prev,before);
   const flagged=await page.locator('#stat-mines').innerText();
   await page.locator('#btn-mode-dig').click();
   await canvas.click({position:{x:615,y:410}});
   await page.waitForFunction(()=>document.querySelector('#stat-progress-percent').textContent.trim()!=='0%');
   const digProgress=await page.locator('#stat-progress-percent').innerText();
   await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
   await page.mouse.down({button:'middle'});await page.mouse.move(box.x+box.width/2+75,box.y+box.height/2+55,{steps:6});await page.mouse.up({button:'middle'});
   await page.mouse.wheel(0,330);await page.locator('#btn-reset-camera').click();
   await page.locator('#slice-x-min').fill('1');await page.locator('#slice-x-min').dispatchEvent('input');
   await page.locator('#btn-reset-slices').click();
   await page.screenshot({path:path.join(__dirname,`${name}-board.jpg`),type:'jpeg',quality:72,fullPage:true});
   await page.locator('#btn-return-lobby').click();await page.locator('#lobby-overlay:not(.hidden)').waitFor();
   assert.equal(await page.locator('body.in-room').count(),0);
   results.push({name,viewport,flagBefore:before,flagAfter:flagged,digProgress,cameraRotateZoomReset:true,sliceReset:true,returnToLobby:true,focusTrap:true,errors,passed:true});
 }
 assert.deepEqual(errors,[]);
 await context.close();console.log(`PASS ${name}`);
}
(async()=>{const b=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{await run(b,'controls-desktop',{width:1440,height:900});await run(b,'controls-mobile',{width:390,height:844},true);fs.writeFileSync(path.join(__dirname,'controls-results.json'),JSON.stringify({browser:b.version(),testedAt:new Date().toISOString(),results},null,2)+'\n');console.log(`CONTROLS_QA=PASS cases=${results.length}`)}finally{await b.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});
