const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const BASE='http://127.0.0.1:8790/';
const results=[];
async function run(browser,name,viewport,mobile=false,locale='en-US') {
  const context=await browser.newContext({viewport,isMobile:mobile,hasTouch:mobile,locale,reducedMotion:'reduce'});
  const page=await context.newPage();
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('response',r=>{if(r.status()>=400&&!/\/favicon\.ico(?:\?|$)/.test(r.url())) errors.push(`${r.status()} ${r.url()}`)});
  await page.goto(BASE,{waitUntil:'networkidle'});
  await page.locator('#btn-task-freeplay').click();
  await page.locator('#input-nickname').fill(name);
  await page.locator('#btn-start-task').click();
  await page.locator('body.in-room').waitFor();
  assert.equal(await page.locator('#tutorial-overlay').evaluate(x=>x.classList.contains('hidden')),true);
  const initialSave=new URL(page.url()).searchParams.get('solo');
  assert.ok(initialSave);
  if(mobile) {
    await page.locator('#btn-mobile-controls').click();
    assert.equal(await page.locator('#control-panel').evaluate(x=>x.classList.contains('mobile-open')),true);
    await page.screenshot({path:path.join(__dirname,`${name}-controls.jpg`),type:'jpeg',quality:72,fullPage:true});
    await page.locator('#btn-mobile-flag').click();
    assert.equal(await page.locator('#btn-mobile-flag').evaluate(x=>x.classList.contains('active')),true);
    await page.locator('#btn-mobile-dig').click();
    await page.locator('#btn-mobile-slices').click();
    assert.equal(await page.locator('#slicing-panel').evaluate(x=>x.classList.contains('mobile-open')),true);
    await page.locator('#btn-close-slices').click();
    await page.locator('#btn-mobile-controls').click();
    await page.setViewportSize({width:844,height:390});
    assert.equal(await page.locator('body.in-room').count(),1);
    await page.setViewportSize(viewport);
  }
  await page.locator('#btn-auto-survey-start').click();
  await page.waitForFunction(()=>{const root=document.querySelector('#tutorial-overlay'),btn=document.querySelector('#btn-tutorial-replay');return root&&!root.classList.contains('hidden')&&btn&&!btn.classList.contains('hidden')},{timeout:45000});
  const winTitle=await page.locator('#tutorial-title').innerText();
  assert.match(winTitle,mobile?/自由模式|清除|完成/:/FREE MODE CLEARED/);
  await page.screenshot({path:path.join(__dirname,`${name}-won.jpg`),type:'jpeg',quality:72,fullPage:true});
  await page.locator('#btn-tutorial-replay').click();
  await page.locator('#replay-hud:not(.hidden)').waitFor();
  if(mobile) assert.equal(await page.locator('#btn-return-lobby').isVisible(),false,'return button overlaps mobile replay HUD');
  await page.locator('#btn-replay-pause').click();
  assert.equal(await page.locator('#btn-replay-pause').getAttribute('aria-pressed'),'true');
  await page.screenshot({path:path.join(__dirname,`${name}-replay-paused.jpg`),type:'jpeg',quality:72,fullPage:true});
  await page.locator('#btn-replay-pause').click();
  assert.equal(await page.locator('#btn-replay-pause').getAttribute('aria-pressed'),'false');
  await page.locator('#btn-replay-exit').click();
  await page.locator('#replay-hud').waitFor({state:'hidden'});
  await page.locator('#btn-tutorial-next').click();
  await page.waitForFunction(()=>document.querySelector('#stat-progress-percent')?.textContent.trim()==='0%'&&document.querySelector('#tutorial-overlay')?.classList.contains('hidden')&&!document.body.classList.contains('replay-active'),null,{timeout:10000});
  const nextSave=new URL(page.url()).searchParams.get('solo');
  assert.equal(await page.locator('body.in-room').count(),1);
  assert.equal(await page.locator('#modal-overlay').evaluate(x=>x.classList.contains('hidden')),true);
  assert.deepEqual(errors,[]);
  results.push({name,viewport,initialSave,nextSave,winTitle,replayPauseResumeExit:true,errors,passed:true});
  await context.close();
  console.log(`PASS ${name}`);
}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{await run(browser,'freeplay-desktop',{width:1440,height:900});await run(browser,'freeplay-mobile',{width:390,height:844},true,'zh-CN');await run(browser,'freeplay-mobile-small',{width:360,height:640},true,'zh-CN');fs.writeFileSync(path.join(__dirname,'freeplay-results.json'),JSON.stringify({browser:browser.version(),testedAt:new Date().toISOString(),results},null,2)+'\n');console.log(`FREEPLAY_QA=PASS cases=${results.length}`)}finally{await browser.close()}})().catch(e=>{console.error(e.stack||e);process.exit(1)});
