const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const BASE='http://127.0.0.1:8790/';
const out=__dirname;
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const errors=[];
  try {
    const hostContext=await browser.newContext({viewport:{width:1440,height:900},locale:'en-US'});
    const guestContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,locale:'zh-CN'});
    const host=await hostContext.newPage();
    const guest=await guestContext.newPage();
    for(const page of [host,guest]) { page.on('pageerror',e=>errors.push(e.message)); page.on('response',r=>{if(r.status()>=400&&!/\/favicon\.ico(?:\?|$)/.test(r.url()))errors.push(`${r.status()} ${r.url()}`)}); }
    await host.goto(BASE,{waitUntil:'networkidle'});
    await host.locator('#btn-lobby-multiplayer').click();
    const squadLobbyArt=await host.locator('#lobby-modal').evaluate(x=>getComputedStyle(x).getPropertyValue('--story-lobby-art').trim());
    await host.screenshot({path:path.join(out,'squad-lobby.jpg'),type:'jpeg',quality:72,fullPage:true});
    await host.locator('#input-nickname').fill('Release Host');
    await host.locator('#btn-create-room').click();
    await host.waitForURL(/room=/);
    const code=new URL(host.url()).searchParams.get('room');
    assert.match(code,/^[A-Z0-9]{6}$/);
    await guest.goto(`${BASE}?room=${code}`,{waitUntil:'networkidle'});
    assert.equal(await guest.locator('#input-room').inputValue(),code);
    await guest.locator('#input-nickname').fill('Release Guest');
    await guest.locator('#btn-join-room').click();
    await guest.locator('#player-list-ul').getByText('Release Guest').waitFor();
    await host.locator('#player-list-ul').getByText('Release Guest').waitFor();
    assert.match(await host.locator('#player-list-ul').innerText(),/Release Host.*Release Guest/s);
    assert.match(await guest.locator('#player-list-ul').innerText(),/Release Host.*Release Guest/s);
    await host.locator('#input-chat').fill('v4.1.0 web release sync');
    await host.locator('#btn-send-chat').click();
    await guest.locator('#chat-messages').getByText(/v4\.1\.0 web release sync/).waitFor();
    const before=await host.locator('#stat-mines').innerText();
    await host.locator('#btn-mode-flag').click();
    const box=await host.locator('#canvas-container canvas').boundingBox();
    await host.locator('#canvas-container canvas').click({position:{x:box.width/2,y:box.height/2}});
    await host.waitForFunction(previous=>document.querySelector('#stat-mines').textContent.trim()!==previous,before);
    const after=await host.locator('#stat-mines').innerText();
    await guest.waitForFunction(expected=>document.querySelector('#mobile-stat-mines').textContent.trim()===expected,after);
    await host.locator('#btn-mode-dig').click();
    await host.locator('#canvas-container canvas').click({position:{x:615,y:410}});
    await host.waitForFunction(()=>document.querySelector('#stat-progress-percent').textContent.trim()!=='0%');
    const digProgress=await host.locator('#stat-progress-percent').innerText();
    await guest.waitForFunction(expected=>document.querySelector('#mobile-stat-progress').textContent.trim()===expected,digProgress);
    await host.screenshot({path:path.join(out,'squad-host.jpg'),type:'jpeg',quality:72,fullPage:true});
    await guest.screenshot({path:path.join(out,'squad-guest.jpg'),type:'jpeg',quality:72,fullPage:true});
    await guest.reload({waitUntil:'networkidle'});
    await guest.locator('body.in-room').waitFor();
    assert.match(await guest.locator('#player-list-ul').innerText(),/Release Host.*Release Guest/s);
    await host.locator('#btn-return-lobby').click();
    await host.locator('#lobby-overlay:not(.hidden)').waitFor();
    await guest.waitForFunction(()=>{const t=document.querySelector('#player-list-ul')?.textContent||'';return t.includes('Release Guest')&&!t.includes('Release Host')});
    const guestAfter=await guest.locator('#player-list-ul').innerText();
    assert.match(guestAfter,/Release Guest.*👑/s);
    assert.deepEqual(errors,[]);
    const result={browser:browser.version(),testedAt:new Date().toISOString(),roomCode:code,squadLobbyArt,hostMembers:'Release Host, Release Guest',chatSynced:true,flagBefore:before,flagAfter:after,digProgress,guestFlagAfter:await guest.locator('#mobile-stat-mines').innerText(),reconnect:true,hostLeaveTransferred:guestAfter,errors,passed:true};
    fs.writeFileSync(path.join(out,'multiplayer-results.json'),JSON.stringify(result,null,2)+'\n');
    console.log(`MULTIPLAYER_QA=PASS room=${code} flag=${after}`);
  } finally { await browser.close(); }
})().catch(e=>{console.error(e.stack||e);process.exit(1)});
